# Generated by Django 4.1.2 on 2022-10-20 21:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('music', '0009_remove_song_album_remove_album_album_cover_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='album',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='img/'),
        ),
    ]
